name: Documentation CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1

      - name: Secret Scan
        uses: gitleaks/gitleaks-action@v2